export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A group of scientists working together to discover a new planet",
  "A doctor performing a complex surgery on a patient",
  "A macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "A person playing a game of chess with an AI",
  "A detective solving a high-profile crime case",
  "An artist creating a sculpture using cutting-edge technology",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A macro photograph of a butterfly on a flower with its wings in motion, surrounded by a bokeh background, digital art",
  "A pilot flying a futuristic aircraft",
  "A teacher using virtual reality in the classroom",
  "A farmer using drones to monitor crops",
  "A musician composing an AI-assisted symphony",
  "A composite image of a lion and a unicorn in a magical forest, with a full moon in the background, digital art",
  "A time-lapse video of a city skyline during a thunderstorm, with lightning illuminating the buildings, digital art",
  "An engineer designing a sustainable city",
  "A journalist uncovering corruption in a government",
  "A lawyer defending human rights in a court of law",
  "An architect designing a eco-friendly skyscraper",
  "A photograph of a group of people participating in a protest march, with a sense of unity and determination, 50mm photography",
  "A composite image of a diver swimming with a group of colorful fish in a coral reef, digital art",
  "An explorer uncovering ancient ruins",
  "An astronaut conducting research on a space station",
  "A fisherman using advanced technology for sustainable fishing",
  "A zookeeper using genetic engineering to conserve endangered species",
  "A chef using molecular gastronomy to create new dishes",
  "A gardener using biotechnology to grow exotic plants",
  "A photographer using AI-assisted cameras to capture stunning landscapes",
  "A designer creating a fashion line using 3D printing",
  "A mountaineer scaling a previously unclimbed mountain",
  "A researcher studying the effects of climate change",
  "A veterinarian using stem cell therapy to treat animals",
  "A composite image of a robot firefighter saving a cat from a burning building, digital art",
  "A time-lapse video of a flower garden blooming throughout the seasons, digital art",
  "A 3D animation of a robot explorer discovering a new planet, with detailed views of the planet's landscapes and inhabitants, digital art",
  "A race car driver driving a self-driving car",
  "A linguist creating a new language using AI",
  "A park ranger using drones to protect wildlife",
  "An archaeologist using virtual reality to explore ancient sites",
  "A geologist using AI to predict natural disasters",
  "A park ranger using AI to predict and prevent forest fires",
  "A 3D animation of a robot astronaut repairing a satellite in orbit, with the Earth in the background, digital art",
  "A panoramic photograph of a mountain range with a beautiful sunset and a rainbow in the background, digital art",
  "A composite image of a futuristic city with flying cars and advanced technology, digital art",
  "A time-lapse video of a starry night sky with a meteor shower, digital art",
  "A 3D animation of a robot farmer using advanced technology to harvest crops, digital art",
  "A composite image of a hot air balloon flying over a picturesque landscape with a beautiful sunset, digital art",
  "A photograph of a group of friends laughing and having fun in a park, 35mm photography",
  "A composite image of a futuristic city with a sustainable transportation system, digital art",
  "A photograph of a person practicing yoga on a beach at sunset, 50mm photography",
  "A composite image of a robot chef creating a new dish using molecular gastronomy, digital art",
  "A time-lapse video of a city skyline during a lightning storm, digital art",
  "A 3D animation of a robot designer creating a fashion line using 3D printing, digital art",
];
